# -*- coding: utf-8 -*-
import autoit
import os
import time
import Variaveis
import log


def InformarPsico(Qtd):
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Informar Dados Psicotropico')
    autoit.send("{F12}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Informar Lote')
    autoit.win_wait_active("[Class:TFRM_ITENSLOTE]", Variaveis.TTelaL)
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Selecionar Lote')
    time.sleep(Variaveis.TDig)
    autoit.send(Qtd)
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.control_click("[Class:TFRM_ITENSLOTE]", "TVSMColorButton1")
    time.sleep(Variaveis.TEnter)

    log.EscreverLog('Informar Dados Receita')
    autoit.win_wait_active("[Class:TFRM_RECEITAMEDICA]", Variaveis.TTelaL)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBButtonEdit2")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Nº de Inscrição (CRM, ect:)')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBButtonEdit2", Variaveis.Medico)
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)
    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit5")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Nome Comprador')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit5", "LUIZ ANTONIO DE SOUZA FILHO")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit4")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Endereço Comprador')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit4", "AV. CENTRAL, 550")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit3")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Numero Documento Comprador')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit3", "27146391")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "Edit2")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('UF Comprador')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "Edit2", "SP")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit8")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Nome Paciente')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit8", "LUIZ ANTONIO DE SOUZA FILHO")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit7")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Endereço Paciente')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit7", "AV. CENTRAL, 550")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBNumericEdit2")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Idade Paciente')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBNumericEdit2", "37")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "Edit4")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Sexo Paciente')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "Edit4", "MASCULINO")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)


    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit9")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Numero Receita')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBEdit9", "1")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)


    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBDateTimeEdit2")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Data Receita')
    time.sleep(Variaveis.TDig)
    autoit.send("{DOWN}")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBSpinEdit2")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Qtde Solicitada')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBSpinEdit2", "30")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)

    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TRzDBSpinEdit1")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TDig)
    autoit.send("{HOME}{SHIFTDOWN}{END}{SHIFTUP}{BACKSPACE}")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Prescrição Diaria')
    time.sleep(Variaveis.TDig)
    autoit.control_send("[Class:TFRM_RECEITAMEDICA]", "TRzDBSpinEdit1", "1,00")
    time.sleep(Variaveis.TEnter)
    autoit.send("{ENTER}")
    time.sleep(Variaveis.TEnter)
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Confirma dados receita')
    time.sleep(Variaveis.TDig)
    autoit.control_click("[Class:TFRM_RECEITAMEDICA]", "TVSMColorButton1")
    time.sleep(Variaveis.TEnter)
    log.EscreverLog('Sai Dados Receita')
    time.sleep(Variaveis.TEnter)